name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/OnePlusOSS/android_kernel_oneplus_sm8250
          branch: oneplus/sm8250_s_12.1
          config: vendor/kona_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          python-2.7: true
          android-version: 12
          aosp-clang-version: r383902
